# Generated by Django 3.1.7 on 2021-05-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_avail',
            name='Book_Edition',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'student'), (2, 'guest'), (3, 'Staff')], default=2),
        ),
    ]
