# Generated by Django 3.2.2 on 2021-06-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0003_books_avail_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_avail',
            name='Book_Category',
            field=models.CharField(default='', max_length=120),
        ),
    ]
